apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: online-event-booking-ayaankhan
data:
  # User Service 
  userEventServiceUrl: "http://new-event-service/api/events"
  userBookingServiceUrl: "http://booking-service/book_ticket"
  # Event Service 
  eventMongoUri: "mongodb://mongodb:27017/new-eventdb"
  # Notification Service 
  notificationMongoUri: "mongodb://mongodb:27017/notifications-service-db"
  notificationRabbitmqUrl: "amqp://guest:guest@rabbitmq:5672"
  notificationCeleryBrokerUrl: "pyamqp://guest:guest@rabbitmq//"
  # Booking Service 
  bookingEventServiceUrl: "http://new-event-service/api/events"
  bookingCeleryBrokerUrl: "pyamqp://guest:guest@rabbitmq//"
  bookingPaymentGatewayUrl: "http://booking-service/payments"

  init.sql: CREATE DATABASE bookingdb;
