apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: OnlineEventBookingAyaanKhan
type: Opaque
data:
  # User
  userDatabaseUrl: cG9zdGdyZXNxbDovL3Bvc3RncmVzOjEyMzQ1Njc4OUBwb3N0Z3Jlczo1NDMyL3VzZXJfc2VydmljZV9kYg==
  userSecretKey: MTIzNDU2Nzg5
  
  # Booking
  bookingDatabaseUrl: cG9zdGdyZXNxbDovL3Bvc3RncmVzOjEyMzQ1Njc4OUBwb3N0Z3Jlczo1NDMyL2Jvb2tpbmdkYg==
  bookingSecretKey: MTIzNDU2Nzg5
